# Tensorflow2.0 小练习

In [2]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [2]:
def softmax(x):
    ##########
    #'''实现softmax函数，只要求对最后一维归一化，
    #不允许用tf自带的softmax函数'''
    exp_x = tf.exp(x)  # 计算每个元素的指数
    sum_exp = tf.reduce_sum(exp_x, axis=-1, keepdims=True)  # 沿最后一个维度求和并保持维度
    prob_x = exp_x / sum_exp  # 归一化得到概率
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [3]:
def sigmoid(x):
    ##########
    
    # '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    # 计算指数项的负数部分
    exp_neg_x = tf.exp(-x)
    # 计算分母并取倒数
    prob_x = 1 / (1 + exp_neg_x)
    ##########
    return prob_x
   

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [ ]:
def softmax_ce(x, label):
    
    
    ##########
    #'''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
   # 添加小常数防止对数中的零值
    epsilon = 1e-10
    x = tf.clip_by_value(x, epsilon, 1.0)
    
    # 计算交叉熵: -sum(label * log(x))
    log_likelihood = -tf.reduce_sum(label * tf.math.log(x), axis=-1)
    
    # 计算平均损失
    loss = tf.reduce_mean(log_likelihood)
    ##########
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [9]:
def sigmoid_ce(x, label):
    ##########
    #'''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    # 添加小常数避免数值不稳定
    epsilon = 1e-10
    x = tf.clip_by_value(x, epsilon, 1.0 - epsilon)
    
    # 计算二元交叉熵: -(label * log(x) + (1-label) * log(1-x))
    loss_per_sample = -(label * tf.math.log(x) + (1.0 - label) * tf.math.log(1.0 - x))
    
    # 计算平均损失
    loss = tf.reduce_mean(loss_per_sample)
    ##########
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]


True